######################
# book (meta) info

title: Recent Trend in Deep Learning Based Natural Language Processing
author: 
  name: Authors

github:
  url: ""


########
# more settings

collections:
  chapters:
      output: false

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

markdown: kramdown
kramdown:
  math_engine: katex
